#node deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  selector:
    matchLabels:
      appName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        appName: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: index.docker.io/elasticsearch:2.4
        ports:
        - containerPort: 9200
        env:
        - name: GET_HOSTS_FROM
          value: dns
      nodeSelector:
        nodetype: service
      terminationGracePeriodSeconds: 10
