#node deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: default
spec:
  selector:
    matchLabels:
      appName: kibana
  replicas: 4
  template:
    metadata:
      labels:
        appName: kibana
    spec:
      containers:
      - name: kibana
        image: index.docker.io/kibana:6.6.1
        ports:
        - containerPort: 5601
        env:
        - name: GET_HOSTS_FROM
          value: dns
      nodeSelector:
        nodetype: service
      terminationGracePeriodSeconds: 10