#node deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: default
spec:
  selector:
    matchLabels:
      appName: logstash
  replicas: 1
  template:
    metadata:
      labels:
        appName: logstash
    spec:
      containers:
      - name: postgres
        image: docker.elastic.co/logstash/logstash:6.6.1
        ports:
        - containerPort: 5432
        env:
        - name: GET_HOSTS_FROM
          value: dns

